### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/bell#2]
Just installed from main in a virtualenv with `pip install .`:

```
bell https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                 Traceback (most recent call last):
  File "/home/matthew/Documents/mantis/bell/bell/bin/bell", line 5, in <module>
    from bell import cli
ImportError: cannot import name 'cli' from 'bell' (unknown location)
```

**Comment by nsorros** [comment]
I do not get that error. Could you describe the steps so that we can reproduce this? I wonder whether this is related with the version of pip?

**Comment by ivyleavedtoadflax** [comment]
I think it was down to my virtualenv actuually. Seems to be resolved after creating a new one.
