### ISSUE TITLE
Add option to capture output of a command

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/bell#6]
It would be nice if we could use Bell to capture the output of an arbitrary command, so that we can report it to slack.

**Comment by nsorros** [comment]
Whats the use case for this?

**Comment by ivyleavedtoadflax** [comment]
> Whats the use case for this?

See hfie-watcher repo. Might be that I just need to reproduce this functionality elsewhere, but see what you think

**Comment by nsorros** [comment]
> > Whats the use case for this?
> 
> See hfie-watcher repo. Might be that I just need to reproduce this functionality elsewhere, but see what you think

From what I can see you want to capture the output from a command that runs but I am still not sure why

**Comment by ivyleavedtoadflax** [comment]
So that we can send it to slack.

**Comment by nsorros** [comment]
> So that we can send it to slack.

And what output is useful to send to slack? what are you trying to do essentially

**Comment by ivyleavedtoadflax** [comment]
I want to report on the hf endpoints we have running. See: https://github.com/MantisAI/hfie-watcher/blob/main/.github/workflows/cronjob.yml
